### ISSUE TITLE
Temperature doesn't change while program is running

### ISSUE THREAD

**Issue by mattmole** [sparkfun/pxt-weather-bit#11]
Hi,

While in a forever loop, I cannot get the temperature to change from the weather:bit board. If I hold my finger over the sensor, the temperature remains constant until I reset the board.

I've tried the "Start Weather Monitoring" in a Start block and Forever block. I've tried the Start weather monitoring in the same forever block and set up. I've tried delays between the setup and reading section...

This is my latest attempt...

![image](https://user-images.githubusercontent.com/10687725/29177706-4c833822-7de7-11e7-8ffe-a4ed947c395d.png)

Thanks

**Comment by ADataDate** [comment]
I won't be able to review this until Tuesday, Aug 15 but one thing I noticed (and I'm not sure if you have all the blocks showing) is that the RX and TX pins of the weather bit are connected to 14 and 15 respectively- so you need a serial redirect block as well. 

I will get this sorted ASAP when I get back. 

Thanks for bringing the issue to my attention.

**Comment by mattmole** [comment]
Ok I'll have a play. Why is this needed please if I'm using the serial over
the USB port?

**Comment by ADataDate** [comment]
Sorry, I thought you were using the serial port on the weather:bit.

**Comment by mattmole** [comment]
No problem.

Let me know when you've looked into the issue I'm having and I'm happy to
do some beta testing if you need me to.

Matt

**Comment by mattmole** [comment]
Hi,

Any thoughts on this please? I'm keen to use the library to send data to a raspberry pi and then process it elsewhere.

Thanks

**Comment by ADataDate** [comment]
Hi, 

We found the issues you were having. We have been working on the fix and the newpackage should be published tomorrow - if not tonight. 

Turns out the weather monitoring mode was set up as "forced" so the values were being stored and not updated without another write the control meas register. 

The work around to get it working until the new package is published is to place the "start weather monitoring" block into a trigger-able event which will reset that control register each time the event is triggered. If you are not using the "soil moisture sensor" you can use P0,  or P19, P20 (if you aren't using the I2C)  to set up a trigger to be controlled by your Raspberry Pi or even on a time delay switching between HIGH and LOW. 

Thanks for bringing this to our attention - I apologize it took some time but you've helped out so Thanks! I'll let you know as soon as the updated package is published and some beta testing would be great!

**Comment by ADataDate** [comment]
New package is published and ready for use! Once I've got your confirmation I'll close this out.

**Comment by mattmole** [comment]
Hi Mary,

That's brilliant news - thanks! No problem that it took a while

Can I test this new version by just using the module in the
https://pxt.microbit.org editor?

Once I've tested the temperature and pressure functions I'll have a play
with the wind sensor functions.

Matt

**Comment by ADataDate** [comment]
Hi Matt, the new site is makecode.microbit.org and the package is ready to be added and used.

**Comment by mattmole** [comment]
Thank you. This works perfectly now

**Comment by bboyho** [comment]
Looks like this is fixed. Thanks @ADataDate !!!! I just tested it out with all three variables. By re-adding the `Weatherbit` package to the example, the temperature, humidity, and pressure started updating in real time so you do not have to keep hitting the micro:bit's reset button. I'll update the code in the tutorial. =)
